pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
        maven {
            url = "https://maven.fabricmc.net/"
        }
    }
    plugins {
        id("com.gradleup.shadow") version "9.4.0"
    }
}

rootProject.name = "SimpleVoice-Geyser"

include("core", "spigot")

